services:
  nginx: 
    build: ./requirements/nginx
    container_name: nginx
    ports: 
      - "443:443"
    env_file:
      - .env
    networks: 
      - incept_net
    depends_on:
      - wordpress
    volumes:
      - incept_vol:/var/www/html/
  wordpress: 
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - incept_net
    volumes:
      - incept_vol:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - incept_net
    env_file:
      - .env
    volumes:
      - incept_db:/var/lib/mysql/
networks:
  incept_net:

volumes:
  incept_vol:
  incept_db: