services:
  nginx: 
    build: ./requirements/nginx
    container_name: nginx
    ports: 
      - "443:443"
    env_file:
      - .env
    networks: 
      - incept_net
    depends_on:
      - wordpress
    volumes:
      - incept_html:/var/www/html/
    restart: always
  wordpress: 
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - incept_net
    volumes:
      - incept_html:/var/www/html/
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - incept_net
    env_file:
      - .env
    volumes:
      - incept_db:/var/lib/mysql/
    healthcheck:
      test: ["CMD-SHELL", "/etc/mysql/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
  redis: 
    build: ./requirements/redis
    container_name: redis
    networks:
      - incept_net
  adminer: 
    build: requirements/adminer
    container_name: adminer
    networks: 
      - incept_net
    volumes: 
      - incept_html:/var/www/html/

networks:
  incept_net:

volumes:
  incept_html:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/fwechsle/data/incept_html


  incept_db:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/fwechsle/data/incept_db
