mysql -u root << EOF
CREATE DATABASE $DB_NAME;
USE $DB_NAME;
CREATE USER '$DB_USER'@'wordpress.$NET_NAME' IDENTIFIED BY '$DB_PW';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'wordpress.$NET_NAME';
FLUSH PRIVILEGES;
EOF